import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

const stats = read('./Stats.jsx')
const settings = read('./Settings.jsx')
const confirmDialog = read('../components/ConfirmDialog.jsx')
const reloadPrompt = read('../components/ReloadPrompt.jsx')
const notFound = read('../components/NotFound.jsx')
const css = read('../index.css')
const indexHtml = read('../../index.html')

describe('cinematic secondary surfaces', () => {
  it('keeps Stats behavior while simplifying the Insights presentation', () => {
    expect(stats).toContain('<h1 className="sr-only">Insights</h1>')
    expect(stats).not.toContain('<h1 className="type-page-title">Insights</h1>')
    expect(stats).toContain('Time with your shows')
    expect(stats).not.toContain('Total time watched')
    expect(stats).toContain('{formatWatchTime(totalMinutes)}')
    expect(stats).toContain('aria-label="Personal insight"')
    expect(stats).not.toContain('Daily insight')
    expect(stats).toContain('Show history')
    expect(stats).toContain('className="stats-summary content-surface')
    expect(stats).toContain('className="stats-insight content-surface')
    expect(stats).toContain('to={`/watching/${show.tmdb_id}`}')
    expect(stats).toContain('className="motion-press block"')
    expect(stats).toContain('aria-label={`Actions for ${show.name}`}')
    expect(stats).not.toContain('className="type-caption">{show.watched} of {show.total}')
    expect(stats).not.toContain('>Complete</span>')
    expect(stats).not.toContain('aria-label={`${show.watched} of ${show.total} episodes watched`}')
    expect(stats).toContain('role="dialog"')
    expect(stats).toContain('aria-modal="true"')
    expect(stats).toContain("if (event.key === 'Escape') onClose()")
    expect(stats).toContain('onClick={(event) => event.stopPropagation()}')
    expect(stats).toContain('onRestore')
    expect(stats).toContain('onRemove')
    expect(stats).not.toContain('bg-black/60')
    expect(stats).not.toContain('text-red-400')
  })

  it('keeps the global atmosphere static, layered, and input-transparent', () => {
    const atmosphere = css.slice(css.indexOf('--canvas-atmosphere:'), css.indexOf('.app-page'))
    expect(css).toContain('--canvas-atmosphere:')
    expect(css).toContain('radial-gradient(ellipse 80% 62% at 18% 0%')
    expect(css).toContain('radial-gradient(ellipse 70% 56% at 92% 8%')
    expect(css).toContain('radial-gradient(ellipse 100% 44% at 50% 100%')
    expect(css).toContain('linear-gradient(to bottom, transparent 0%, transparent 68%')
    expect(atmosphere).not.toContain('animation:')
    expect(atmosphere).not.toContain('filter: blur(')
    expect(css).not.toContain('background-attachment: fixed')
    expect((css.match(/background:\s*var\(--canvas-atmosphere\);/g) ?? []).length).toBe(1)
    expect(css).toContain('body {')
    expect(css).toContain('background-size: 100% 100%;')
    expect(css).toContain('#root {\n  min-height: 100%;\n}')
    expect(css).toContain('.app-shell {')
    expect(css.slice(css.indexOf('.app-shell {'), css.indexOf('.app-page'))).not.toContain('background:')
    expect(css).toContain('pointer-events: none')
    expect(css).toContain('prefers-reduced-transparency: reduce')
  })

  it('keeps first paint and runtime canvas treatments synchronized', () => {
    expect(indexHtml).toContain('meta name="theme-color" content="#080b14"')
    expect(indexHtml).toContain('--canvas-atmosphere:')
    expect(indexHtml).toContain(':root {\n        background: #080b14;\n      }')
    expect(indexHtml).toContain('body {\n        background: var(--canvas-atmosphere);')
    expect(indexHtml).toContain('background-size: 100% 100%;')
    expect(indexHtml).toContain('class="app-loading-shell"')
    expect(css).toContain('background: var(--canvas-atmosphere);')
    expect(css).toContain('html {\n  min-height: 100%;\n  background-color: var(--color-canvas);\n}')
    expect(css).toContain('.app-shell {')
    expect(css).toContain('max-width: 42rem;')
  })

  it('keeps Settings controls and backup workflows while using grouped semantic roles', () => {
    expect(settings).toContain('className="settings-group surface-group')
    expect(settings).toContain('surface-interactive')
    expect(settings).toContain('type="file"')
    expect(settings).toContain('className="hidden"')
    expect(settings).toContain('<select')
    expect(settings).toContain('PREFERRED_HOUR_OPTIONS')
    expect(settings).toContain('status-banner--destructive')
    expect(settings).toContain('aria-live={live ? \'polite\' : undefined}')
    expect(settings).not.toContain('border-red-400')
    expect(settings).not.toContain('bg-red-400')
  })

  it('keeps system UI semantics and recovery actions intact', () => {
    expect(confirmDialog).toContain('role="alertdialog"')
    expect(confirmDialog).toContain('aria-modal="true"')
    expect(confirmDialog).toContain('onClick={onConfirm}')
    expect(confirmDialog).toContain("if (e.key === 'Escape') onCancel()")
    expect(reloadPrompt).toContain('role="status" aria-live="polite"')
    expect(reloadPrompt).toContain('onClick={onUpdate}')
    expect(reloadPrompt).toContain('onClick={onDismiss}')
    expect(notFound).toContain('to="/"')
    expect(css).toContain('background: var(--color-overlay);')
    expect(css).toContain('border-radius: var(--radius-overlay);')
    expect(css).toContain('box-shadow: var(--elevation-overlay);')
  })
})
