create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  identity text not null unique,
  tmdb_show_id bigint not null,
  season_number integer not null check (season_number > 0),
  episode_number integer not null check (episode_number > 0),
  notification_type text not null,
  claimed_at timestamptz not null default now(),
  claim_token uuid null,
  delivered_at timestamptz null,
  created_at timestamptz not null default now(),
  unique (tmdb_show_id, season_number, episode_number, notification_type)
);

alter table public.notification_deliveries enable row level security;
revoke all on public.notification_deliveries from anon, authenticated;

create or replace function public.claim_episode_notification_deliveries(
  p_tmdb_show_id bigint,
  p_episodes jsonb,
  p_claim_token uuid,
  p_claimed_at timestamptz
)
returns table(identity text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with requested as (
    select
      (value->>'season_number')::integer as season_number,
      (value->>'episode_number')::integer as episode_number,
      value->>'notification_type' as notification_type
    from jsonb_array_elements(p_episodes)
  ), upserted as (
    insert into public.notification_deliveries (
      identity, tmdb_show_id, season_number, episode_number, notification_type,
      claimed_at, claim_token
    )
    select
      p_tmdb_show_id || ':' || season_number || ':' || episode_number || ':' || notification_type,
      p_tmdb_show_id, season_number, episode_number, notification_type,
      p_claimed_at, p_claim_token
    from requested
    on conflict (tmdb_show_id, season_number, episode_number, notification_type)
    do update set claimed_at = excluded.claimed_at, claim_token = excluded.claim_token
    where notification_deliveries.delivered_at is null
      and notification_deliveries.claimed_at < p_claimed_at - interval '30 minutes'
    returning notification_deliveries.identity, notification_deliveries.claim_token
  )
  select upserted.identity from upserted where upserted.claim_token = p_claim_token;
end;
$$;

revoke all on function public.claim_episode_notification_deliveries(bigint, jsonb, uuid, timestamptz)
  from public, anon, authenticated;
grant execute on function public.claim_episode_notification_deliveries(bigint, jsonb, uuid, timestamptz)
  to service_role;
