-- Phase 2: automatic episode-available notifications, built on the Phase 1
-- Web Push channel (see 20260719120000_add_push_subscriptions.sql and
-- 20260719130000_unschedule_legacy_notification_cron.sql).
--
-- Two additions:
--
-- 1. An activation watermark on push_subscriptions. Deploying Phase 2 must
--    never backfill every old unwatched episode the moment it ships — only
--    episodes whose resolved release instant is strictly after a
--    subscription's watermark are ever eligible for an automatic push. A
--    Phase-1-only subscription stays at automatic_notifications_enabled_at =
--    null (never activated) until the Phase 2 client runs and activates it
--    (api/push/subscribe.js), so nothing changes for it until then.
--
-- 2. Subscription-scoped delivery dedup. The Phase 1 notification_deliveries
--    table dedupes only by show/season/episode/type, which is wrong once
--    delivery is automatic and per-subscription: two installs must each get
--    their own delivery record for the same episode, and removing one
--    subscription must never block or affect another's claims. That table
--    was added in Phase 1 but never written to (see CLAUDE.md — Phase 1 only
--    ever sent one manually-triggered test push, which doesn't use this
--    table at all), so there is no production data to migrate and it's
--    replaced outright rather than patched column-by-column.

alter table public.push_subscriptions
  add column if not exists automatic_notifications_enabled_at timestamptz null;

comment on column public.push_subscriptions.automatic_notifications_enabled_at is
  'Set once — the first time this installation activates automatic episode notifications (api/push/subscribe.js), backdated by a small grace window. Null means automatic notifications have never been activated for this subscription. Only episodes whose resolved release instant is strictly after this timestamp are ever eligible for an automatic push, so activation can never backfill old unwatched episodes.';

drop function if exists public.claim_episode_notification_deliveries(bigint, jsonb, uuid, timestamptz);

drop table if exists public.notification_deliveries;

create table public.notification_deliveries (
  id bigint generated by default as identity primary key,
  identity text not null unique,
  push_subscription_id bigint not null references public.push_subscriptions (id) on delete cascade,
  tmdb_show_id bigint not null,
  season_number integer not null check (season_number > 0),
  episode_number integer not null check (episode_number > 0),
  notification_type text not null,
  claimed_at timestamptz not null default now(),
  claim_token uuid null,
  delivered_at timestamptz null,
  created_at timestamptz not null default now(),
  unique (push_subscription_id, tmdb_show_id, season_number, episode_number, notification_type)
);

alter table public.notification_deliveries enable row level security;
revoke all on public.notification_deliveries from anon, authenticated;

comment on column public.notification_deliveries.push_subscription_id is
  'Which installation this delivery claim/record belongs to. On delete cascade: removing a subscription (disable, or stale-subscription cleanup after a 404/410 from the push service) removes its undelivered claims with it, so nothing left behind ever errors or blocks a fresh subscription from being notified again.';

-- Atomically claims a batch of episodes (all belonging to one show) for one
-- subscription, so concurrent worker invocations can never double-send:
-- inserting is the only way a row is created, and re-claiming an
-- already-delivered row is impossible (the WHERE clause excludes it). A
-- claim left undelivered (in-flight, or a transient send failure) becomes
-- reclaimable after 10 minutes — matched to the worker's ~10-15 minute cron
-- cadence, so a transient failure retries within a run or two without racing
-- an invocation that's still actively sending.
create or replace function public.claim_episode_notification_deliveries(
  p_push_subscription_id bigint,
  p_tmdb_show_id bigint,
  p_episodes jsonb,
  p_claim_token uuid,
  p_claimed_at timestamptz
)
returns table(season_number integer, episode_number integer, notification_type text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with requested as (
    select
      (value->>'season_number')::integer as season_number,
      (value->>'episode_number')::integer as episode_number,
      value->>'notification_type' as notification_type
    from jsonb_array_elements(p_episodes)
  ), upserted as (
    insert into public.notification_deliveries (
      identity, push_subscription_id, tmdb_show_id, season_number, episode_number,
      notification_type, claimed_at, claim_token
    )
    select
      p_push_subscription_id || ':' || p_tmdb_show_id || ':' || season_number || ':' || episode_number || ':' || notification_type,
      p_push_subscription_id, p_tmdb_show_id, season_number, episode_number, notification_type,
      p_claimed_at, p_claim_token
    from requested
    on conflict (push_subscription_id, tmdb_show_id, season_number, episode_number, notification_type)
    do update set claimed_at = excluded.claimed_at, claim_token = excluded.claim_token
    where notification_deliveries.delivered_at is null
      and notification_deliveries.claimed_at < p_claimed_at - interval '10 minutes'
    returning notification_deliveries.season_number, notification_deliveries.episode_number,
      notification_deliveries.notification_type, notification_deliveries.claim_token
  )
  select upserted.season_number, upserted.episode_number, upserted.notification_type
  from upserted where upserted.claim_token = p_claim_token;
end;
$$;

revoke all on function public.claim_episode_notification_deliveries(bigint, bigint, jsonb, uuid, timestamptz)
  from public, anon, authenticated;
grant execute on function public.claim_episode_notification_deliveries(bigint, bigint, jsonb, uuid, timestamptz)
  to service_role;
