-- Native Web Push subscriptions (Phase 1: manual test notification only).
--
-- This app has no auth (single-user, public/anon Supabase access — see
-- CLAUDE.md). Unlike tracked_shows/watched_episodes, push subscription
-- endpoints and keys are secret-bearing: anyone who read a row could send
-- arbitrary browser push traffic pretending to be Rerun's server, or target
-- the owner's device. So this table is locked down harder than the rest of
-- the schema — RLS is enabled and every privilege is revoked from anon and
-- authenticated. All reads/writes happen exclusively through Vercel
-- serverless endpoints (api/push/*.js) using the Supabase service-role key,
-- which never reaches the browser.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_test_sent_at timestamptz null
);

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon, authenticated;

comment on table public.push_subscriptions is
  'Web Push subscriptions for the installed Rerun PWA. Server-only access (service role); never publicly readable.';
